server:
  port: 8090

spring:

  thymeleaf:
    mode: LEGACYHTML5
    cache: false

  datasource:
    url: jdbc:mysql://sly-net:33006/noah?characterEncoding=utf8&useSSL=false
    username: noah
    password: noah
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath*:com/**/mapper/*.xml

